### ISSUE TITLE
makemessages not working

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-speakup#293]
The management script is failing because of the dash: https://github.com/liqd/a4-speakup/blob/dfbac953f6486ef6a2f870ecdf8731adbbfc645e/apps/contrib/management/commands/makemessages.py#L38

**Comment by fuzzylogic2000** [comment]
`venv/bin/python manage.py makemessages -d djangojs
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/katharina/a4-speakup/apps/contrib/management/commands/makemessages.py", line 24, in handle
    return super().handle(*args, **options)
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/commands/makemessages.py", line 384, in handle
    potfiles = self.build_potfiles()
  File "/home/katharina/a4-speakup/venv/lib/python3.7/site-packages/django/core/management/commands/makemessages.py", line 424, in build_potfiles
    file_list = self.find_files(".")
  File "/home/katharina/a4-speakup/apps/contrib/management/commands/makemessages.py", line 38, in find_files
    path.relpath(get_module_dir('a4-speakup'))
  File "/home/katharina/a4-speakup/apps/contrib/management/commands/makemessages.py", line 10, in get_module_dir
    return path.dirname(module.__file__)
  File "/usr/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
make: *** [Makefile:94: po] Error 1
`

**Comment by fuzzylogic2000** [comment]
@rmader I couldn't find how to make os work with our strange directory name or what the problem is there. As we need to translate stuff, we need it to work, though. My solution would be to rename the directory to a4_speakup. Do you have an easier solution?
